#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-07-13 09:49:52.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_max_path_depth() works", {

  expect_error(
    kwb.file:::get_max_path_depth()
    # non-character argument
  )

})

