#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-07-13 09:49:51.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("add_file_info() works", {

  expect_error(
    kwb.file:::add_file_info()
    # argument "data" is missing, with no default
  )

})

