#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2018-12-16 07:54:59.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("paste_path_parts() works", {

  expect_error(
    kwb.file:::paste_path_parts()
    # argument "path_parts" is missing, with no default
  )

})

