#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("read_file_metadata() works", {

  expect_error(
    kwb.file:::read_file_metadata()
    # argument "yaml_file" is missing, with no default
  )

})

