#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2018-12-16 07:54:58.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("dir_full_recursive_xml() works", {

  expect_error(
    kwb.file:::dir_full_recursive_xml()
    # argument "root" is missing, with no default
  )

})

