#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("copy_files_to_target_dir() works", {

  expect_error(
    kwb.file:::copy_files_to_target_dir()
    # argument "target_dir" is missing, with no default
  )

})

test_that("get_download_dir() works", {

  kwb.file:::get_download_dir()

})

test_that("to_simple_names() works", {

  expect_error(
    kwb.file:::to_simple_names()
    # argument "paths" is missing, with no default
  )

})

