#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-07-13 09:49:52.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("split_paths() works", {

  expect_error(
    kwb.file:::split_paths()
    # argument "paths" is missing, with no default
  )

})

