#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("write_file_info_to_yaml_file() works", {

  expect_error(
    kwb.file:::write_file_info_to_yaml_file()
    # argument "source_paths" is missing, with no default
  )

})

test_that("file_paths_to_file_info() works", {

  expect_error(
    kwb.file:::file_paths_to_file_info()
    # argument "file_paths" is missing, with no default
  )

})

test_that("file_info_to_yaml() works", {

  expect_error(
    kwb.file:::file_info_to_yaml()
    # argument "file_info" is missing, with no default
  )

})

