#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2018-12-16 07:55:00.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("write_file_info_to_yaml_file() works", {

  expect_error(
    kwb.file:::write_file_info_to_yaml_file()
    # argument "source_paths" is missing, with no default
  )

})

