#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("dir_full() works", {

  kwb.file:::dir_full()

})

test_that("dir_full_recursive_xml() works", {

  expect_error(
    kwb.file:::dir_full_recursive_xml()
    # argument "root" is missing, with no default
  )

})

